name: Master test pipeline

on: [push]

jobs:
  stage_1:
    name: Smoke test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Execute stage 1
      continue-on-error: true
      run: |
          pip install pytest pytest-cov
          pytest -rf tests.py | awk '/FAILED/{print $2}' >> quarantine.txt && sort -o quarantine.txt -u quarantine.txt
    - name: Update quarantine list
      uses: actions/upload-artifact@v4
      with:
        name: quarantine list
        path: quarantine.txt

  stage_2:
    name: Acceptance test
    needs: stage_1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Get quarantine list
        uses: actions/download-artifact@v4
        with:
          name: quarantine list
      - name: Execute stage 2
        continue-on-error: true
        run: |
          pip install pytest pytest-cov
          pytest -rf tests.py | awk '/FAILED/{print $2}' >> quarantine.txt && sort -o quarantine.txt -u quarantine.txt
      - name: Update quarantine list
        uses: actions/upload-artifact@v4
        with:
          name: quarantine list
          path: quarantine.txt

  stage_3:
    name: Regression test
    needs: stage_2
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Get quarantine list
        uses: actions/download-artifact@v4
        with:
          name: quarantine list
      - name: Execute stage 3
        continue-on-error: true
        run: |
          pip install pytest pytest-cov
          pytest -rf tests.py | awk '/FAILED/{print $2}' >> quarantine.txt && sort -o quarantine.txt -u quarantine.txt
      - name: Update quarantine list
        uses: actions/upload-artifact@v4
        with:
          name: quarantine list
          path: quarantine.txt
